-- Add sample card data
-- IMPORTANT: card_number_hash values MUST correspond to the hashing algorithm used in CardServiceImpl
-- The hashes below are SHA-256 of the plain card numbers generated by Java's MessageDigest and HexFormat.of().formatHex()

-- Assume these customers exist in a related (but undefined here) customer table
DO $$
DECLARE
    Customer1 VARCHAR := 'CUST123';
    Customer2 VARCHAR := 'CUST456';
    CurrentYear INT := EXTRACT(YEAR FROM CURRENT_DATE);
    CurrentMonth INT := EXTRACT(MONTH FROM CURRENT_DATE);
    ExpiryDate1 DATE;
    ExpiryDate2 DATE;
    ExpiryDate3 DATE;
BEGIN
    -- Calculate expiry dates
    ExpiryDate1 := make_date(CurrentYear + 1, CurrentMonth, 1);
    ExpiryDate2 := make_date(CurrentYear + 2, CurrentMonth, 1);
    ExpiryDate3 := make_date(CurrentYear - 1, CurrentMonth, 1);

    -- Card 1: Belongs to Customer1, PRE_ACTIVATED, expires next year
    IF NOT EXISTS (SELECT 1 FROM cards.card WHERE card_number_hash = 'c2db08fafa547ba20281e08e237680d7bc2e54e0f833a1bab296b89cce884d8d') THEN
        INSERT INTO cards.card (card_number_hash, last_four_digits, cardholder_name, expiry_date, status, customer_id)
        VALUES (
            'c2db08fafa547ba20281e08e237680d7bc2e54e0f833a1bab296b89cce884d8d', -- SHA-256 of '1111222233334444'
            '4444',
            'Alice Smith',
            ExpiryDate1, -- Expires first day of month next year
            'PRE_ACTIVATED',
            Customer1
        );
        RAISE NOTICE 'Inserted card ending 4444 for CUST123.';
    ELSE
        RAISE NOTICE 'Card ending 4444 already exists.';
    END IF;

    -- Card 2: Belongs to Customer2, ACTIVE, expires in 2 years
    IF NOT EXISTS (SELECT 1 FROM cards.card WHERE card_number_hash = '316450a869799877d4606e6726c781637d16f79297c1394c8969a6a5902c8f87') THEN
        INSERT INTO cards.card (card_number_hash, last_four_digits, cardholder_name, expiry_date, status, customer_id, activation_date)
        VALUES (
            '316450a869799877d4606e6726c781637d16f79297c1394c8969a6a5902c8f87', -- SHA-256 of '5555666677778888'
            '8888',
            'Bob Johnson',
            ExpiryDate2, -- Expires first day of month in 2 years
            'ACTIVE',
            Customer2,
            CURRENT_TIMESTAMP -- Activated now (for seeding purposes)
        );
        RAISE NOTICE 'Inserted card ending 8888 for CUST456.';
    ELSE
        RAISE NOTICE 'Card ending 8888 already exists.';
    END IF;

    -- Card 3: Belongs to Customer1, ACTIVE but Expired last year (for testing)
    IF NOT EXISTS (SELECT 1 FROM cards.card WHERE card_number_hash = '86097f933de6d9d20ff8c8273e0c3a5efb80e82c41eda0a7cdf2bb6a31eff8e5') THEN
        INSERT INTO cards.card (card_number_hash, last_four_digits, cardholder_name, expiry_date, status, customer_id, activation_date)
        VALUES (
            '86097f933de6d9d20ff8c8273e0c3a5efb80e82c41eda0a7cdf2bb6a31eff8e5', -- SHA-256 of '9999000011112222'
            '2222',
            'Alice Smith',
            ExpiryDate3, -- Expired last year
            'EXPIRED', -- Set status explicitly as expired
            Customer1,
            CURRENT_TIMESTAMP - INTERVAL '2 years' -- Activated 2 years ago
        );
        RAISE NOTICE 'Inserted card ending 2222 for CUST123 (Expired).';
    ELSE
        RAISE NOTICE 'Card ending 2222 already exists.';
    END IF;
END $$; 